name: TrickOrTreat
main: io.github.jisaacs1207.trickortreat.TrickOrTreat
version: 1.0
author: jisaacs1207
website: http://fivekingdoms.net
depend: [Vault,WorldGuard,WorldEdit]
description: >
             Trick or treat with your friends!

commands:
   tot:
      description: Tricks or treats!
      aliases: [tot]